name: ernteliste
description: A Solawi Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  server:
    path: server
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  week_of_year: ^2.2.0
  date_checker: ^1.0.0
  http: ^1.1.0
  sqflite: any
  path: any
  provider: ^6.0.5
  universal_platform: ^1.0.0+1
  universal_io: ^2.2.2
  collection: ^1.18.0
  calendar_date_picker2:
    git:
      url: https://github.com/Lotharla/calendar_date_picker2.git
      ref: main
    # path: ../calendar_date_picker2
  logging: ^1.2.0
  url_launcher: ^6.2.6
  scroll_to_index: ^3.0.1
  pdf:
  path_provider:
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
