name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.3.0
  path: any
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.0
  sqflite: any
  sqflite_common_ffi: any
  sqflite_common_ffi_web: any
  week_of_year: ^2.2.0
  http: ^1.1.0
  universal_platform: ^1.0.0+1
  characters:
  intl:
  date_checker: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
